version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - 8081:8081
      - 8082:8082  
    volumes:
      - ./data/repositories:/repositories
      - ./data/artifactory:/var/opt/jfrog/artifactory
    environment:
      - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g -Djavax.net.ssl.trustStore=/var/opt/jfrog/artifactory/etc/cacerts -Djavax.net.ssl.trustStorePassword=changeit
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    network_mode: "host"
