version: '2.2'
services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio-docker-local-storage-vol
    ports:
      - "4873:4873"
    volumes:
        - "./storage:/verdaccio/storage"
        - "./conf:/verdaccio/conf"
    network_mode: "host"
volumes:
  verdaccio:
    driver: local
